_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  # ROI_HEADS:
  #   NUM_CLASSES: 2
  ROI_MASK_HEAD:
    # MASK_DCT_ON: True
    # MASK_LOSS_WEIGHT: 0.007
    MASK_INITIAL_ON: False
    REFINEMASK_ON: True
# SOLVER:
#   IMS_PER_BATCH: 2
#   # BASE_LR: 0.02
#   BASE_LR: 0.0025
#   STEPS: (60000, 80000)
#   MAX_ITER: 90000

DATASETS:
  TRAIN: ("coco_2017_train",)
  # TEST: ("coco_2017_val",)
  # TEST: ("lvis_v1_val_cocofied",)
  # TEST: ("coco_2017_train",)
  TEST: ("coco_2017_test-dev",)


SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
