_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  # ROI_HEADS:
  #   NUM_CLASSES: 2

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
  # TEST: ("coco_2017_train",)

SOLVER:
  IMS_PER_BATCH: 2
  # BASE_LR: 0.02
  BASE_LR: 0.0025
  STEPS: (60000, 80000)
  MAX_ITER: 90000

# SOLVER:
#   IMS_PER_BATCH: 16
#   BASE_LR: 0.02
#   STEPS: (60000, 80000)
#   MAX_ITER: 90000

